# Generated by Django 4.2.13 on 2024-11-11 02:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickChatRoom',
            fields=[
                ('quick_room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quick_room_name', models.CharField(default='default_room_name', max_length=100)),
                ('quick_created_at', models.DateTimeField(auto_now_add=True)),
                ('quick_participants', models.JSONField(default=list)),
                ('quick_departure', models.CharField(default='default_departure', max_length=255)),
                ('quick_destination', models.CharField(default='default_destination', max_length=255)),
                ('quick_departure_time', models.DateTimeField(blank=True, null=True)),
                ('quick_recruitment_complete', models.BooleanField(default=False)),
                ('quick_is_active', models.BooleanField(default=True)),
                ('quick_timer_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuickQuickChatRoom',
            fields=[
                ('quickquick_room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quickquick_room_name', models.CharField(default='default_room_name', max_length=100)),
                ('quickquick_created_at', models.DateTimeField(auto_now_add=True)),
                ('quickquick_participants', models.JSONField(default=list)),
                ('quickquick_departure', models.CharField(default='default_departure', max_length=255)),
                ('quickquick_destination', models.CharField(default='default_destination', max_length=255)),
                ('quickquick_departure_time', models.DateTimeField(blank=True, null=True)),
                ('quickquick_recruitment_complete', models.BooleanField(default=False)),
                ('quickquick_is_active', models.BooleanField(default=True)),
                ('quickquick_chat_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuickQuickChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('quickquick_message', models.TextField()),
                ('quickquick_timestamp', models.DateTimeField(auto_now_add=True)),
                ('quickquick_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_chat.quickquickchatroom')),
            ],
        ),
        migrations.CreateModel(
            name='QuickChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quick_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_chat.quickchatroom')),
            ],
        ),
    ]
