# Generated by Django 4.2.13 on 2024-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0002_quickchatroom_quick_final_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchatroom',
            name='settlement_complete',
            field=models.BooleanField(default=False),
        ),
    ]
