# Generated by Django 4.2.13 on 2024-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0003_quickchatroom_settlement_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchatroom',
            name='quick_is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
