# Generated by Django 4.2.13 on 2024-11-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0004_quickchatroom_quick_is_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickchatroom',
            name='settlement_complete',
        ),
    ]
