# Generated by Django 4.2.13 on 2024-11-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0005_remove_quickchatroom_settlement_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickchatroom',
            options={'ordering': ['-quick_created_at'], 'verbose_name': 'Quick Chat Room', 'verbose_name_plural': 'Quick Chat Rooms'},
        ),
        migrations.AddField(
            model_name='quickchatroom',
            name='quick_max_participants',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='quickchatroom',
            name='quick_min_participants',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='quickchatroom',
            name='quick_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
