# Generated by Django 4.2.13 on 2024-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0006_alter_quickchatroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchatroom',
            name='quick_participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
