# Generated by Django 4.2.13 on 2024-11-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0007_quickchatroom_quick_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchatroom',
            name='quick_final_participants_saved',
            field=models.BooleanField(default=False),
        ),
    ]
