# Generated by Django 4.2.13 on 2024-07-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_userinfo_user_remove_chatroom_departure_lat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
