# Generated by Django 4.2.13 on 2024-08-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_id'], name='chat_chatro_room_id_c3a3db_idx'),
        ),
    ]
