# Generated by Django 4.2.13 on 2024-08-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatroom_chat_chatro_room_id_c3a3db_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='ChatRoomData',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_room_id_c3a3db_idx',
        ),
    ]
