# Generated by Django 4.2.13 on 2024-08-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_chatmessage_chatroomdata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoomData',
            new_name='ChatMessage',
        ),
    ]
