# Generated by Django 4.2.13 on 2024-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_chatroomdata_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='recruitment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.JSONField(default=list),
        ),
    ]
