# Generated by Django 4.2.13 on 2024-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chatroom_recruitment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='settlement_complete',
            field=models.BooleanField(default=False),
        ),
    ]
