# Generated by Django 4.2.13 on 2024-10-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatroom_settlement_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='departure_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
