# Generated by Django 4.2.13 on 2024-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chatroom_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
