# Generated by Django 4.2.13 on 2024-10-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_chatmessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
