# Generated by Django 4.2.13 on 2024-11-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_chatroom_active_chatroom_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='final_participants',
            field=models.JSONField(default=list),
        ),
    ]
