# Generated by Django 4.2.13 on 2024-11-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatroom_final_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='final_participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
