# Generated by Django 4.2.13 on 2024-11-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatreview',
            old_name='participant_id',
            new_name='reviewed_user_id',
        ),
        migrations.RemoveField(
            model_name='chatreview',
            name='review_text',
        ),
    ]
