# Generated by Django 4.2.13 on 2024-11-12 01:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quick_chat', '0005_remove_quickchatroom_settlement_complete'),
        ('reviews', '0002_rename_participant_id_chatreview_reviewed_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickChatReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('reviewed_user_id', models.CharField(max_length=100)),
                ('review_score', models.PositiveSmallIntegerField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reviews', to='quick_chat.quickchatroom')),
            ],
        ),
    ]
